# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0006_auto_20170719_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futuretreadingdata',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='optiontreadingdata',
            options={'ordering': ['-time']},
        ),
    ]
