# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0010_intervals_current_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('code', models.FloatField(default=0, verbose_name='价格')),
            ],
        ),
    ]
