# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0014_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousDayFutureTreadingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('open_price', models.FloatField(default=0, verbose_name='开盘价')),
                ('max_price', models.FloatField(default=0, verbose_name='最高价')),
                ('min_price', models.FloatField(default=0, verbose_name='最低价')),
                ('close_price', models.FloatField(default=0, verbose_name='收盘价')),
            ],
            options={
                'abstract': False,
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='ContinuousFuture',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='期货代码')),
                ('type', models.CharField(max_length=20, verbose_name='期货种类')),
                ('delivery_day', models.DateField(null=True, verbose_name='交割日')),
            ],
        ),
        migrations.AddField(
            model_name='continuousdayfuturetreadingdata',
            name='future',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.ContinuousFuture', verbose_name='对应期货'),
        ),
    ]
