# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0015_auto_20170925_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuousfuture',
            name='delivery_day',
        ),
    ]
